name: Push File

on: push

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create pull request
      uses: heshamghalaab/deployment-to-another-repo@v1
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: 'MainFolder'
        destination_repo: 'heshamghalaab/secondaryRepo'
        destination_folder: 'Files'
        destination_base_branch: 'main'
        destination_head_branch: 'develop'
        user_email: 'hesham_ghalaab@hotmail.com'
        user_name: 'heshamghalaab'
        pull_request_reviewers: ''
        
 
