name: Deploy Files
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Deploy Files
    steps:
      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: github.com
          private-key: ${{ ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDAeIn8kVRvibRXEOXQunsD2sycwtczPxQYe0ntMCI3b2YpWCAB91EYt4Eopl3uP4j0gKOBgnn677r6kyzI+IKRNIpmRDRJuO87LYvotOH4nUHwqcbF5mELs3Ohty3KlhUYnr8ENGJu4gDLh6ZabWTStpwr9AAmsXNKIoFgyr+fzR+AhJQYCHTEtkWZr+23jxSpUqgnn8Rqz7UQhsvOLbebFZzBQ1iMRSrkJQjygJsk/krftVQiG+DqC6atnXVvnXcmb87gDRr6Y51ZQSkXRvnSOMw6lVmcO69OrUiC2CaCA7GtKzTQNCbcbNenvTFBw0wklDv8cST7negGFiFSat+96MgtAw+0hiIx3y1S4JbFRwJkGl7IfUkN89MSLeezwnXICT0gxD4S/LQVNZUXs15TdgO91GwnpmanpTx17ZEMED5BDmxbFU81FDurzsN4LxOBDKpR1vdQSzKWRCeXgFYEBAZF5FuVkDPNXCaUOT9hiRe5+YdSzNpJKrOLbXKNECCsW9dUtBD4QtkwVrDwLbDRJzxBneQZ0Da4MFCO1CGQFDa9ixZcJ3kBPgOpsv7KsRczKrHqzeSxgz+sC+FKrNo5wVwVaj6bmHal0O544V/jRcoxtSnIO4PzWI2TQpOQg4alXXMQ7UhAl3z+c24+FVUDFksYrpu+Re2LYacQHeoKSw== Generated by Sourcetree on macOS for heshamghalaab-GitHub }}

      - name: Checkout the commit
        uses: actions/checkout@v2

      - name: Deploy
        uses: manzoorwanijk/action-deploy-to-repo@master
        with:
          src_dir: build
          target_owner: heshamghalaab
          target_repo: secondaryRepo
          target_dir: Files
          target_branch: main
          # Optional
          # access_token: ${{ secrets.GITHUB_ACCESS_TOKEN }} # Not needed when using SSH
          cleanup_command: "rm -rf assets/* && rm -f assets/asset-manifest.json"
