name: Deploy Files
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Deploy Assets
    steps:
      - name: Checkout the commit
        uses: actions/checkout@v2

      - name: Deploy
        uses: manzoorwanijk/action-deploy-to-repo@master
        with:
          src_dir: build
          target_owner: heshamghalaab
          target_repo: secondaryRepo
          target_dir: Files
          target_branch: main # default
          # Optional
          access_token: ${{ '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' }}
          cleanup_command: "rm -rf assets/* && rm -f assets/asset-manifest.json"
